[tool.poetry]
name = "selenium-tests"
version = "0.1.0"
description = ""
authors = ["wojtiwojt"]

[tool.poetry.dependencies]
python = "^3.9"
selenium = "^4.1.0"
requests = "^2.2"
black = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
