# Generated by Django 3.2.9 on 2022-02-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="cover_url",
            new_name="url",
        ),
    ]
