# Generated by Django 3.2.9 on 2022-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_rename_cover_url_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
