# Generated by Django 3.2.9 on 2022-02-27 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0004_auto_20220227_1943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="article_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="article_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
