# Generated by Django 3.2.9 on 2022-02-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_auto_20220227_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="articles.article",
            ),
        ),
    ]
