# Generated by Django 3.2.9 on 2022-04-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "__first__"),
        ("articles", "0006_alter_source_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="article_tags", to="tags.Tag"
            ),
        ),
    ]
