name: Run black and tests on Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-black-and-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build django container
        run: |
          docker-compose build django
      - name: Run black on django
        run: |
          docker-compose run --entrypoint "poetry run black --check --verbose pozabanka/" django 
      - name: Run tests on django
        run: |
          docker-compose run --entrypoint "poetry run pytest pozabanka/" django
      - name: Build selenium tests containers
        run: |
          docker-compose build selenium-tests
      - name: Run black on selenium
        run: |
          docker-compose run --entrypoint "poetry run black --check --verbose selenium-tests/" selenium-tests 
      - name: Run selenium tests
        run: |
          docker-compose run --entrypoint "poetry run pytest" selenium-tests

