name: Run black and tests on Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-black-and-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build container
        run: |
          docker-compose build django
      - name: Run black
        run: |
          docker-compose run --entrypoint "poetry run black --check --verbose pozabanka/" django 
      - name: Run tests 
        run: |
          docker-compose run --entrypoint "poetry run pytest pozabanka/" django

