name: Run black and tests

on: push

defaults:
 run:
  working-directory: ./django

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.9"
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies 
        run: |
          poetry install
      - name: Run black
        run: |
          poetry run black --diff ./pozabanka

