name: Run black and tests

on: push

defaults:
 run:
  working-directory: ./django

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.9"
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies 
        run: |
          poetry install
      - name: Run black
        run: |
          poetry run black --check --verbose ./pozabanka
      - name: Create dummy .env file
        run: |
          echo "SECRET_KEY=secret-key-for-actions-purposes" >> .env
          echo "EMAIL_HOST=smtp.gmail.com" >> .env
          echo "EMAIL_PORT=587" >> .env
          echo "EMAIL_HOST_USER=test@gmail.com" >> .env
          echo "EMAIL_HOST_PASSWORD=dummypassword" >> .env
          echo "EMAIL_USE_TLS=True" >> .env
          echo "EMAIL_USE_SSL=False" >> .env
      - name: Run pytest on django
        run: |
          cd pozabanka
          echo "SECRET_KEY=secret-key-for-actions-purposes" > .env
          poetry run pytest

